### ISSUE TITLE
部署之后显示成功了,但是class并没有改变

### ISSUE THREAD

**Issue by SampsonJava** [xxxtai/ArthasHotSwap#15]

**Comment by Gtixlb** [comment]
类修改完毕后，重新编译一下，或者整个项目重新编译一下，再右键选择“ArthasHotSwap”的“Swap this class”，

ArthasHotSwap插件热部署使用的是class文件，修改没有编译，class源文件不会变化

**Comment by SampsonJava** [comment]
最终原因是因为本地jdk与服务器jdk不一致, 并且使用了lambda表达式导致生产的方法名不一致无法热部署class
