### ISSUE TITLE
安装arthashot swap必须顺带安装smart input

### ISSUE THREAD

**Issue by Aresxiao** [xxxtai/ArthasHotSwap#21]
Hello，在idea中安装插件，提示必须一起安装smartinput，可是我不想安装smartinput插件啊。有啥办法吗
![image](https://user-images.githubusercontent.com/3815317/228451336-432882c0-903c-44a3-8323-de04266e3fe9.png)

**Comment by xxxtai** [comment]
如果不需要smart input可以离线安装纯净版：https://github.com/xxxtai/ArthasHotSwap/releases/tag/%E7%BA%AF%E5%87%80%E7%89%88
